Success to connect db: 12.1.0.2.0
Update cyto_sample_mutation set id_cyto_mut =  1065  where id_cyto_mut =  1128 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  1128 ;
Update cyto_sample_mutation set id_cyto_mut =  510  where id_cyto_mut =  1229 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  1229 ;
Update cyto_sample_mutation set id_cyto_mut =  125  where id_cyto_mut =  138 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  138 ;
Update cyto_sample_mutation set id_cyto_mut =  1370  where id_cyto_mut =  1375 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  1375 ;
Update cyto_sample_mutation set id_cyto_mut =  512  where id_cyto_mut =  1472 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  1472 ;
Update cyto_sample_mutation set id_cyto_mut =  1549  where id_cyto_mut =  1702 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  1702 ;
Update cyto_sample_mutation set id_cyto_mut =  1549  where id_cyto_mut =  1735 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  1735 ;
Update cyto_sample_mutation set id_cyto_mut =  1567  where id_cyto_mut =  1737 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  1737 ;
Update cyto_sample_mutation set id_cyto_mut =  199  where id_cyto_mut =  201 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  201 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  392 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  392 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  611 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  611 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  612 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  612 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  613 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  613 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  615 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  615 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  616 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  616 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  617 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  617 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  618 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  618 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  619 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  619 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  620 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  620 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  621 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  621 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  844 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  844 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  852 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  852 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  859 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  859 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  919 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  919 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  921 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  921 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  923 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  923 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  926 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  926 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  949 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  949 ;
Update cyto_sample_mutation set id_cyto_mut =  391  where id_cyto_mut =  953 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  953 ;
Update cyto_sample_mutation set id_cyto_mut =  538  where id_cyto_mut =  627 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  627 ;
Update cyto_sample_mutation set id_cyto_mut =  548  where id_cyto_mut =  641 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  641 ;
Update cyto_sample_mutation set id_cyto_mut =  555  where id_cyto_mut =  643 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  643 ;
Update cyto_sample_mutation set id_cyto_mut =  559  where id_cyto_mut =  645 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  645 ;
Update cyto_sample_mutation set id_cyto_mut =  561  where id_cyto_mut =  635 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  635 ;
Update cyto_sample_mutation set id_cyto_mut =  600  where id_cyto_mut =  637 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  637 ;
Update cyto_sample_mutation set id_cyto_mut =  622  where id_cyto_mut =  846 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  846 ;
Update cyto_sample_mutation set id_cyto_mut =  622  where id_cyto_mut =  864 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  864 ;
Update cyto_sample_mutation set id_cyto_mut =  622  where id_cyto_mut =  924 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  924 ;
Update cyto_sample_mutation set id_cyto_mut =  622  where id_cyto_mut =  928 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  928 ;
Update cyto_sample_mutation set id_cyto_mut =  622  where id_cyto_mut =  951 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  951 ;
Update cyto_sample_mutation set id_cyto_mut =  649  where id_cyto_mut =  816 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  816 ;
Update cyto_sample_mutation set id_cyto_mut =  886  where id_cyto_mut =  887 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  887 ;
Update cyto_sample_mutation set id_cyto_mut =  890  where id_cyto_mut =  892 ;
delete from cyto_mutation_temp1 where id_cyto_mut =  892 ;
